### ISSUE TITLE
D-4 Ionic app fails to load properly during development and when making changes to source code

### ISSUE THREAD

**Issue by dimitrispy1** [rThamb/soen390-schoolmap#80] opened 2020-03-01 21:59 UTC
**Describe the bug**
Making changes to our source code usually causes the Ionic app to not load properly. Icons, buttons and transitions will fail to load properly.

**To Reproduce**
1. Start Ionic app
2. Make changes to source code
3. Save changes
4. Reload localhost Ionic app 

**Expected behavior**
Once changes are made to the source code, the Ionic app should reload properly and reflect the changes made.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1803
 - Browser: Chrome
 - Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional info**
Temporary solution: Close browser/tab and reopen localhost

**Comment by nickode** [comment] 2020-03-28 06:14
This is not a bug with our app, its a bug with chrome dev tools when you reload the page while having the console open. The fix for this is to close the console, refresh the page and then you can reopen the console, if needed.

**Closed by nickode** 2020-03-28 06:14 UTC
Labels: Low Priority, bug
